### ISSUE TITLE
W3C score not displayed

### ISSUE THREAD

**Issue by dedece35** [Accenture/EcoSonar#11]
Hi @alicehaupais,

I launched an analysis but I have no W3C metrics on left column.
Could you tell me why, please ?

![Capture d’écran 2023-03-01 à 10 48 26](https://user-images.githubusercontent.com/12011401/222104743-d3803ec6-0419-4fa3-a3ea-311aac5e2181.png)

**Comment by alicehaupais** [comment]
Hello,

Yes W3C Validator audit is by default disabled because the library used makes an external API call to provide to perform the audit. We chose to disable it to let the choice to the team to use it or not.
For W3C configuration, you can enable it through environment configuration, please follow instructions [here](https://github.com/Accenture/EcoSonar/tree/main/EcoSonar-API#w3c-validator)

**Comment by dedece35** [comment]
My first test isn't OK. sorry :( 

here is the result after activation of environment variable.
<img width="1304" alt="Capture d’écran 2023-03-01 à 23 15 45" src="https://user-images.githubusercontent.com/12011401/222277631-87ffca02-45e6-4123-b0e1-0ebcb6af04e8.png">

Here are logs in EcoSonar API : 
```
ecosonar_api    | Lighthouse Analysis ended for url https://www.pagesjaunes.fr/annuaire/chercherlespros?quoiqui=resto&ou=Rennes+%2835000%29&univers=pagesjaunes&idOu=L03523800
ecosonar_api    | W3C ANALYSIS : launching analyse for https://www.pagesjaunes.fr/annuaire/chercherlespros?quoiqui=resto&ou=Rennes+%2835000%29&univers=pagesjaunes&idOu=L03523800
ecosonar_api    | W3C ANALYSIS : https://www.pagesjaunes.fr/annuaire/chercherlespros?quoiqui=resto&ou=Rennes+%2835000%29&univers=pagesjaunes&idOu=L03523800 has been removed from result 
ecosonar_api    | W3C ANALYSIS : URL https://www.pagesjaunes.fr/annuaire/chercherlespros?quoiqui=resto&ou=Rennes+%2835000%29&univers=pagesjaunes&idOu=L03523800 cannot be found
ecosonar_api    | W3C - None of the urls analysed could be inserted
ecosonar_api    | W3C INSERT - w3c insertion failed
ecosonar_api    | LIGHTHOUSE INSERT - analysis has been insert
ecosonar_api    | GREENIT INSERT - analysis has been insert
ecosonar_api    | BEST PRACTICES INSERT - best practices have been inserted
```

other test with same error in logs : 
```

ecosonar_api    | Lighthouse Analysis ended for url https://www.pagesjaunes.fr/
ecosonar_api    | W3C ANALYSIS : launching analyse for https://www.pagesjaunes.fr/ 
ecosonar_api    | W3C ANALYSIS : https://www.pagesjaunes.fr/ has been removed from result 
ecosonar_api    | W3C ANALYSIS : URL https://www.pagesjaunes.fr/ cannot be found
ecosonar_api    | W3C - None of the urls analysed could be inserted
ecosonar_api    | W3C INSERT - w3c insertion failed
ecosonar_api    | LIGHTHOUSE INSERT - analysis has been insert
ecosonar_api    | GREENIT INSERT - analysis has been insert
ecosonar_api    | BEST PRACTICES INSERT - best practices have been inserted
```

W3C seems to not find my URL exposed on the web https://www.pagesjaunes.fr/ 
Why ?

thank you.

**Comment by alicehaupais** [comment]
Hello @dedece35 

It seems like the website https://www.pagesjaunes.fr/ is blocking the W3C Validator Audit to run. 
If you want to run this audit outside of EcoSonar, you can use the following link : https://validator.w3.org/.
When I tried to run an audit on your page, I received a 403 status code :
![image](https://user-images.githubusercontent.com/48716381/222370022-a0f4d6c7-379f-4308-9134-06d2b6dc2f9d.png).

Currently EcoSonar only supports the use of the W3C Validator API to perform the audits. However we added into our roadmap to remove that dependencies (retrieving directly the HTML code to run the audit) and that should resolve the bug you encountered.
I will let you know in this issue when it's resolved.

**Comment by dedece35** [comment]
hi @alicehaupais,

thank you for analysis.
after internal discussion, I agree with you, we have some blocking systems to avoid some attacks. We should open W3C input to get this metric.

It's ok for me.
