### ISSUE TITLE
"The index path corresponding to the specified order-by item is excluded." when trying to retrieve analysis

### ISSUE THREAD

**Issue by ewanklomp** [Accenture/EcoSonar#21]
Whenever I want to retrieve the EcoSonar analysis on my project I get the following error messages. 

![image](https://github.com/Accenture/EcoSonar/assets/16072932/e9a5b1e9-cdfa-4a7e-8670-b6d53a697ccb)

After some debugging I found out that I am getting back a 500 Internal server error on the following API call: 
/api/greenit/project?projectName=<Project_name>

The specific error it produces is: "The index path corresponding to the specified order-by item is excluded."
![image](https://github.com/Accenture/EcoSonar/assets/16072932/95f120b6-23d0-4ff3-852c-d84763880ab2)

After some analysis I found out that this is a specific issue for the CosmoDB implementation for mongoDB:
https://learn.microsoft.com/en-us/answers/questions/258032/the-index-path-corresponding-to-the-specified-orde
https://learn.microsoft.com/en-us/answers/questions/385230/the-index-path-corresponding-to-the-specified-orde

I am guessing it has something to do with the find commands in this function: https://github.com/Accenture/EcoSonar/blob/main/EcoSonar-API/dataBase/greenItRepository.js#L109

(It happens for all analysis, not only for greenit but also for lighthouse and wc3). 

As my javascript and mongodb knowledge is limited I can't fix it so I am curious whether you understand what is going on and how to fix it.

**Comment by alicehaupais** [comment]
Hello Ewan,
As per our discussion, I have updated the Github documentation to include MongoDB collections setup : https://github.com/Accenture/EcoSonar/tree/main/EcoSonar-API#mongodb-collections

In your case, you will need to define in the terraform scripts the collections with their related indexes.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_mongo_collection
