### ISSUE TITLE
Modifier la licence

### ISSUE THREAD

**Issue by bordage** [Accenture/EcoSonar#7]
Bonjour,

Les facteurs d'impacts utilisés dans GreenIT-Analysis ne sont pas sous licence libre.

Afin de respecter les droits d'auteurs, pouvez-vous, svp, ajouter dans la section "About" et dans le fichier "LICENCE" 

<<
Les facteurs d'impacts environnementaux (quantités de gaz à effet de serre et d'eau) ne sont pas sous licence libre. Tous droits réservés. © Frédéric Bordage. Merci de demander l'autorisation à son auteur pour les utiliser : [fbordage@greenit.fr](mailto:fbordage@greenit.fr) .
>>

Je vous laisse traduire en anglais si besoin.

Merci.

**Comment by alicehaupais** [comment]
Bonjour,

Comme précedemment évoqué, nous avons pour l'instant retirer le calcul des facteurs d'impact environnementaux.
Nous recherchons actuellement une méthode de calcul qui pourrait être plus applicable dans un contexte international.
Nous reviendrons vers vous pour demander l'autorisation d'utiliser la licence si besoin.

Cordialement,

Alice Haupais
