### ISSUE TITLE
Problem to run this tool :(

### ISSUE THREAD

**Issue by dedece35** [Accenture/EcoSonar#8]
Ho @alicehaupais,

I am very interested by your tool ... but I didn't successed to run it.
Unfortunately, I followed differents README.md of EcoSonar-API and EcoSonar plugin and USER_GUIDE.md but with no succes.

Here is my environment and my tests : 
- [ OK ] installation of EcoSonar API (on docker or local npm) on port 3000 + MongoDB Atlas instance) => `http://localhost:3000` OK
- [ OK ] build and install SonarQube plugin on a local SonarQube (local or docker installation) on different versions (8.3, 8.5, 8.9, 9.3 and 9.9) on port 9000 (`http://localhost:9000` OK) => check plugin installation ok in marketplace tab on SonarQube (version 3.1-SNAPSHOT of plugin)
- [ NON OK ] creation of a new project directly on SonarQube UI, then go to project and clic on `EcoSonar URL Configuration` menu, but an error occurs (please see attached file bottom) `Page extension failed`
- [ OK ] launch analyse of a custom project and send metrics to SonarQube with maven command
- [ NON OK ] got to this project, and then clic on the same menu (or `EcoCode Analyis` or `EcoCode Best Practices`), but the same erros occurs

I tested with different versions of SonarQube. My local github clone is up-to-date.

How can I debug the problem or check that my all installation is OK ?
For me, all is OK and there is no errors in logs neither in SonarQube nor EcoSonar API nor when I launch maven analysis of my project.

<img width="1310" alt="Capture d’écran 2023-02-27 à 19 13 45" src="https://user-images.githubusercontent.com/12011401/221670704-b44a0cd2-d821-4165-a44a-4d3e9e89d1b2.png">
<img width="1310" alt="Capture d’écran 2023-02-27 à 19 14 13" src="https://user-images.githubusercontent.com/12011401/221670731-2c57f994-2f99-4c09-b12a-1ec8a4f4530a.png">

I have these logs on API EcoSaonr when I launch my analysis with maven on my project : 
```
INSERT ANALYSIS - Launch analysis for project fr.pagesjaunes.front:front-pj-contribution
GREENIT INSERT - project has no url to do the audit. Audit stopped
```
What is this mean ? a configuration problem ?

**Comment by alicehaupais** [comment]
Hello David,

I was able to replicate your bug. It is linked to an environment variable that is not rightfully set into the SonarQube plugin.
Before doing the command 'mvn clean package', could you please run the following command : 
set REACT_APP_BASE_URL_ECOSONAR_API=http://localhost:3000 (Windows)
OR export REACT_APP_BASE_URL_ECOSONAR_API=http://localhost:3000 (Linux/Mac)

It will add as system environment variable the EcoSonar API URL to be reached by the plugin.
I will update the documentation accordingly. Please let me know if that solution worked.

Regarding your second question, yes it is a configuration problem. To launch an EcoSonar analysis, you need first to declare the pages you wish to audit. You can do that through the 'EcoSonar configuration Page' or with the API Endpoint 'Insert URL into Project'. You can find the user guide available [here](https://github.com/Accenture/EcoSonar/blob/main/USER_GUIDE.md), to guide with the use of EcoSonar.

Please let me know if you have further questions.

**Comment by dedece35** [comment]
Hi @alicehaupais,

yes now all is OK. thank you !
Another suggestion, to make it easy to test your tool (and all its environment), I created locally a docker-compose to install  EcoSonar API, build the plugin SonarQube, install this plugin in an internal SonarQube instance et launch it.
Then I can launch manually a local analysis with maven on a personal project. All is ok.
If you want I can do a PR to check it.

After testing it, as I understand, the tool needs an url exposed to launch its analysis (like a temporary deployed webapp in CI/CD Chain).
But locally, my webapp must be launched, then I configure its url in SonarQube (on SonarQube project), then I launch local analysis which will produce an EcoSonar Anlysis pointing to this local url.
Am I right ?

**Comment by alicehaupais** [comment]
Hello @dedece35 ,

I would be happy to review your docker-compose script and integrate it into our repo. That could be very helpful for the future projects using EcoSonar.

Yes you are correct. The goal is to launch an analysis on a web app in a dev environment and EcoSonar scores could be used as condition to push to production mode.

I confirm you can locally run EcoSonar Analysis on local url (example : http://localhost:3001).
